# Generated by Django 4.1 on 2024-06-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=20)),
                ("lastName", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="toppings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topping_name", models.CharField(max_length=50)),
                ("ingredients", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PizzaFlavor", models.CharField(max_length=50)),
                (
                    "topping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP1.toppings"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=20)),
                ("lastName", models.CharField(max_length=20)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="APP1.agent"
                    ),
                ),
            ],
        ),
    ]
